version: '3.8'

services:
  healthprovider-mongodb:
    container_name: healthprovider-mongodb-container
    image: mongo:latest
    restart: always  # Ensures it restarts on failure
    volumes:
      - mongodb_data:/data/db  # Named volume (avoids Windows permission issues)
    environment:
      MONGO_INITDB_DATABASE: healthprovider-service
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge

volumes:
  mongodb_data:  # Named volume (no manual folder setup needed)